#!/usr/bin/env bash

if [ -f ./.env ]; then
    source ./.env
fi

function configure_composer_auth {
    AUTH_JSON='{"github-oauth": {"github.com": "%s"} }'

    export COMPOSER_AUTH=$(printf "$AUTH_JSON" "${GITHUB_PERSONAL_ACCESS_TOKEN}")
}

docker run --rm -it \
    -u $(id -u):$(id -g) \
    -v $(pwd):/usr/src/myapp \
    -w /usr/src/myapp \
    -e COMPOSER_AUTH="$COMPOSER_AUTH" \
    tombenevides/xdebug-composer:php-8.2 "$@"